### ISSUE TITLE
Startup Failed

### ISSUE THREAD

**Issue by paxsue** [avanteGarbage/DuoMed#1]
Thank you for making this - it's not working for me, unfortunately. I'm trying to run it on a Windows Surface Pro 9 with a PS5 DualSense Controller.

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Duolingo-style gamification -- visual audio and haptic feedback:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\255048658\__init__.py", line 4, in <module>
    from .answer_effects import *
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\255048658\answer_effects.py", line 31, in <module>
    xinput = ctypes.windll.xinput1_1  # Load Xinput.dll
  File "ctypes", line 444, in __getattr__
  File "ctypes", line 374, in __init__
FileNotFoundError: Could not find module 'xinput1_1' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by avanteGarbage** [comment]
Hmm that's strange, I'm using a pretty similar machine. Do you know what version of DirectX you're using? 

I'll keep looking into it, but you should be able to run the addon without rumble now if you replace your answer_effects.py file with the version I just pushed. [link](https://github.com/avanteGarbage/DuoMed/blob/main/answer_effects.py)

**Comment by paxsue** [comment]
Thank you - confirming I can run the addon with the file you provided. I'm using DirectX 12 on Windows 11.
