### ISSUE TITLE
Add-on settings 

### ISSUE THREAD

**Issue by eggvelyn** [avanteGarbage/DuoMed#9]
Hi,
"Tools --> Add-ons --> Duolingo-style gamification --> Settings" gives me an error. Here is the debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.2.1-x86_64-i386-64bit

Traceback (most recent call last):
  File "aqt.addons", line 985, in onConfig
  File "/Users/evelyn/Library/Application Support/Anki2/addons21/255048658/settings_window.py", line 96, in DuoMedSettings
    d = MyUIDialog()
  File "/Users/evelyn/Library/Application Support/Anki2/addons21/255048658/settings_window.py", line 90, in __init__
    QDialog.__init__(self, parent, aqt.Qt.Window)
AttributeError: type object 'Qt' has no attribute 'Window'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Duolingo-style gamification -- visual audio and haptic feedback ['255048658', 2024-03-03T10:28, 'None', '']

===IDs of active AnkiWeb add-ons===
255048658

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-02-26T20:37, 'None', '']
Cloze Overlapper for 23x ['1784155610', 2024-02-17T17:53, 'None', '']
Image Editor ['307397307', 2022-09-07T21:09, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
Yomichan Forvo Server ['580654285', 2023-08-30T13:53, 'None', mod]

**Comment by avanteGarbage** [comment]
should be fixed in the next update!
